### PR TITLE
ENG-184 - Updated yaml api links, icons and readme's command

### PR DESCRIPTION
**Pull request by sunny-trip-ninja**
- Updated readme.md for the deprecated command
- Updated Tripninja logo for the docs
- Updated Elastic beanstalk preprod link to https://preprodapi.tripninja.io

### CODE REVIEW

**Comment by mschembri-TN** [comment]
Task linked: [ENG-184 Try out redoc to see if the docs update when the command runs](https://app.clickup.com/t/14197839/ENG-184)

**Review by abdallahkaram1994 — COMMENTED** [review]
@sunny-trip-ninja This seems fine, but you might want to change the command to have it as .yml instead of .yaml and make it more something like _tn_api_example_file.yml_, just so it's a bit more clear. Comparing the before and after, it seems like the changes work as intended.

**Comment by sunny-trip-ninja** [comment]
@abdallahkaram1994 comment resolved

**Review by abdallahkaram1994 — APPROVED** [review]
Looks good, approved.

**Pull request merged**
