### PR TITLE
EPD-3001 | API Docs v2 |  Create fare structure core docs

### PR DESCRIPTION
**Pull request by rob-dumont**
Changes:
- Created the pages for Overview, Setup, Get Searches and Generate Content for FareStructure
- Use redoc react component to display the openapi docs
- Created openapi files for each endpoint and converted to json format
- Created custom Redoc.css and theme objects to override standard redoc styles
- Reverted React to a previous version to be compatible with Redoc react package
- Created Sidebar component, layout and styling
- Create Pagination footer component 

Notes:
- Actual content of the docs (e.g req/rsp structures and field descriptions) will be finetuned in a future card.

### CODE REVIEW

**Comment by mschembri-TN** [comment]
Task linked: [EPD-3001 API Docs | Create FareStructure (Core) UI](https://app.clickup.com/t/14197839/EPD-3001)

**Review by abdallahkaram1994 — APPROVED** [review]

**Review by simheather — APPROVED** [review]

**Comment by simheather** [comment]
localQA in progress

**Comment by simheather** [comment]
LocalQA looking nice! couple very minor things:
- The designs show a Next Page pointing to Support/FAQ in the pagination on the Generate Solutions page, this is missing on the branch
- V Minor: I wonder if there's a way to remove / reformat this content type part in redocly? looks a bit messy here 
Screen Shot 2023-04-18 at 11 14 40 AM
maybe we could address it in a future ticket?

**Comment by rob-dumont** [comment]
> LocalQA looking nice! couple very minor things:
> 
> * The designs show a Next Page pointing to Support/FAQ in the pagination on the Generate Solutions page, this is missing on the branch
> * V Minor: I wonder if there's a way to remove / reformat this content type part in redocly? looks a bit messy here
>   Screen Shot 2023-04-18 at 11 14 40 AM
>   maybe we could address it in a future ticket?

Cool - let's leave out the support link for now until that page is created. And agreed on the on styling of that bit - I'll make a new ticket to clean it up, since it might be a bit of a pain lol

**Pull request merged**
