### PR TITLE
feature/CU-vdf0y1-docs-for-pricing

### PR DESCRIPTION
**Pull request by mcclymont-k**
**DESCRIPTION**
This is the docs for the price confirmation on hotels - it also includes the removal of pricing.
See the PR for MCFS here: https://github.com/trip-ninja-inc/trip_ninja_api/pull/1227

**TESTING**
1. Compare with MCFS.
2. Check spelling and wording.

### CODE REVIEW

**Comment by trip-ninja-inc** [comment]
Task linked: [CU-vdf0y1 docs for pricing](https://app.clickup.com/t/vdf0y1)

**Review by ziggybabybeauty — APPROVED** [review]
reviewed against PR & MCFS branch and looks good

**Comment by andrescollart** [comment]
Are these not required?

image


Reviewed everything else, approved otherwise.

**Comment by mcclymont-k** [comment]
Fixed @andrescollart, the super_trip_id is not required as the first price will not have one yet

**Review by andrescollart — APPROVED** [review]

**Pull request merged**
