### PR TITLE
EPD-1888 | Flight doc response update

### PR DESCRIPTION
**Pull request by vickchungg**
## Description
ClickUp Ticket: click [here](https://app.clickup.com/t/14197839/EPD-1888)

## Changes
* Updated fields for flight response where include_itineraries = true or false

## How to Test
1. Checkout this branch and run `npx @redocly/openapi-cli preview-docs tn_api_spec.yml`
2. Go to http://127.0.0.1:8080/ > Flight Request
3. Go through all the responses to make sure the fields match up to the postman responses.

### CODE REVIEW

**Comment by mschembri-TN** [comment]
Task linked: [EPD-1888 Flight Doc Response Update](https://app.clickup.com/t/14197839/EPD-1888)

**Review by rob-dumont — APPROVED** [review]

**Review by forampatel96tripninja — APPROVED** [review]
Looks good to me

**Comment by forampatel96tripninja** [comment]
localQA in progress

**Comment by forampatel96tripninja** [comment]
LocalQA ❌

**missing following fields:**
```
"priced_passengers_standard_code": [
                        "ADT"
                    ],
```

**Notes:**
In postman, there isn't `credential_info > itx`

image

No field `flights > "fare_basis_code": "LP7J2LBS",`

image

no `percentage` under `cancel_penalty` and `change_penalty`

image

**Comment by vickchungg** [comment]
> 

Fixed extra/missing fields! For `cancel penalty` and `change_penalty`, seems like the `percentage` and `amount` fields are optional. I've added an optional tag for clarification! 
image

Please let me know if anything else is missing.

**Comment by forampatel96tripninja** [comment]
LocalQA ✅ 
200 response sample includes all mandatory fields.
206 response includes failed routes

**Pull request merged**
