### PR TITLE
Feature/#6jhuwk new search response

### PR DESCRIPTION
**Pull request by niloufarmp**

### CODE REVIEW

**Comment by trip-ninja-inc** [comment]
Task linked: [CU-6jhuwk Design new MCFS response structure for segment mix+match](https://app.clickup.com/t/6jhuwk)

**Review by andrescollart — CHANGES_REQUESTED** [review]
**Lets chat through the new structure overall before you make these changes. I think there are ways we could simplify it.** 

few changes needed for /search/ request:
1. enumerate options for: cabin_class, stops, baggage, region, 
2. add maximum for num_results
3. add the response structure for search_response/brands
4. Description for all of these is the same, as is the type (String)
image

**Comment by niloufarmp** [comment]
> search

Are we changing the request structure as well?

**Comment by niloufarmp** [comment]
> 4\. Description for all of these is the same, as is the

I applied all of these except adding the brands. It's just very big and time consuming, not even in the original response doc. Please review this and I will add brands in another branch?

**Review by mcclymont-k — APPROVED** [review]
I have reviewed - there are some small issues with styling and a few descriptions that could be better, but I am assuming we will be updating these docs as we implement search and VI...

**Comment by mcclymont-k** [comment]
Is the flextrip response going to be unchanged? @niloufarmp

**Comment by mcclymont-k** [comment]
Should this be a number? 
image

and this an array:
image

And this should be an array of objects:
image

**Comment by niloufarmp** [comment]
> Is the flextrip response going to be unchanged? @niloufarmp

Oh good catch, It is going to change as well. I will update this.

**Comment by andrescollart** [comment]
I'm having some difficulty with determining values for some of these, specifically the VI ones where there is no VI segment. Are they simply not returned or are they null? @niloufarmp

**Comment by niloufarmp** [comment]
> these

I'm confused, what do you mean by there is no VI segment? Are you looking for these?
image

**Comment by andrescollart** [comment]
> > these
> 
> I'm confused, what do you mean by there is no VI segment? Are you looking for these?
> image

Sorry not that there's no VI. When a segment is not a VI segment, what are the proper values for things like option_id, option_part, vi_type, vi_position? Or are they not present?

**Comment by niloufarmp** [comment]
> option_id, option_part, vi_type, vi_position
- I think it's best if they are not present when virtual_interline is false. Since they are part of something that is not built yet.

**Review by mcclymont-k — APPROVED** [review]

**Review by andrescollart — APPROVED** [review]

**Pull request merged**
