### PR TITLE
feature/#CU-gmw008-Update-MCFS-docs-for-super-trip-adjustments

### PR DESCRIPTION
**Pull request by niloufarmp**
### Changes
- Updated existing endpoints to support super trip
- Added new endpoint for super trip part deletion
- Added new endpoint for super trip nickname addition

### CODE REVIEW

**Comment by mcclymont-k** [comment]
I think maybe here the flight needs to be itinerary? 
image

**Comment by mcclymont-k** [comment]
Do we have to have part in this endpoint or can we just extract it from the request data? 
image

**Comment by niloufarmp** [comment]
> I think maybe here the flight needs to be itinerary?
> image

Yes I will update this

**Comment by niloufarmp** [comment]
> Do we have to have part in this endpoint or can we just extract it from the request data?
> image

It means the request is attempting to delete a part. to distinguish the url and display clear meaning. I'm afraid (DELETE) super_trip/{id}/part would be confused with deleting a super trip.

**Review by mcclymont-k — APPROVED** [review]

**Comment by mcclymont-k** [comment]
> > Do we have to have part in this endpoint or can we just extract it from the request data?
> > image
> 
> It means the request is attempting to delete a part. to distinguish the url and display clear meaning. I'm afraid (DELETE) super_trip/{id}/part would be confused with deleting a super trip.

Yeah that makes sense!

**Comment by trip-ninja-inc** [comment]
Task linked: [CU-gmw008 Update MCFS docs for super trip adjustments](https://app.clickup.com/t/gmw008)

**Review by Iceman997 — APPROVED** [review]

**Pull request merged**
