### PR TITLE
feature/#CU-b8rdqb-Research-what-is-required-for-ticket-issuance-on-Travelport-and-Amadeus

### PR DESCRIPTION
**Pull request by niloufarmp**
Added ticketing endpoint

### CODE REVIEW

**Comment by trip-ninja-inc** [comment]
Task linked: [CU-b8rdqb Research what is required for ticket issuance on Travelport and Amadeus](https://app.clickup.com/t/b8rdqb)

**Review by mcclymont-k — APPROVED** [review]

**Review by andrescollart — CHANGES_REQUESTED** [review]
image
The "unable to add trip to ticketing queue" needs to be changed to "unable to issue ticket" since here we're not queueing but actually doing the ticketing.

**Comment by niloufarmp** [comment]
> image
> The "unable to add trip to ticketing queue" needs to be changed to "unable to issue ticket" since here we're not queueing but actually doing the ticketing.

Oh this is actually fixed in a later commit. I forgot to change the snapshot tho. If you run it locally, you'll see a different message

**Comment by niloufarmp** [comment]
> unable to issue ticket

Fixed
image

**Review by andrescollart — APPROVED** [review]

**Pull request merged**
