### PR TITLE
EPD-4758 | Adding OTP fields

### PR DESCRIPTION
**Pull request by Sanpele**
## LocalQA approved by
@carson-ricca-tn 
## Description
* Added new OTP fields for include_itineraries: true and include_itineraries: false responses. 

The new fields are
* `risk_profile`
* `cancellation_probability`
* `average_delay_time`
* `self_transfer_time`
* `is_international`

Ticket : https://app.clickup.com/t/14197839/EPD-4758

## How to Test

1. Checkout this branch
2. Run  `npx @redocly/openapi-cli preview-docs tn_api_spec.yml`
3. Go to http://127.0.0.1:8080
4. The fields are in different locations depending on whether the example is selected for include_intineraries: true and include_itineraries: false. Start with include_itineraries false
Screenshot 2023-10-13 at 4 08 33 PM
5. Open up `fare_structure ->  segments` and search for `risk_profile`. The field should be present and accounted for.
6. Now close segment and open the `flight_details` list.
7. Search for `cancellation_probability` The other 4 new fields should be present and accounted for.
8. Done with include_itineraries false. Now select one of the include_itineraries: true responses. 
9. Open `fare_structure -> itineraries -> segments` look for `risk_profile` field, all 5 of the new fields should be present!
10. Verify the descriptions make sense and are sensible.
11. Now go to the response samples in the right section and perform the same steps with the response samples. Verifying the fields are present in the right location for include_itineraries: true / false.

### CODE REVIEW

**Comment by mschembri-TN** [comment]
Task linked: [EPD-4758 Flight Search | Update documentation for fields added from OTP ](https://app.clickup.com/t/14197839/EPD-4758)

**Review by carson-ricca-tn — APPROVED** [review]
LGTM

**Review by sunny-trip-ninja — APPROVED** [review]

**Comment by carson-ricca-tn** [comment]
localQA in progress

**Comment by carson-ricca-tn** [comment]
localQA ✅ everything is looking good!

**Pull request merged**
